### ISSUE TITLE
Building fails on Windows 

### ISSUE THREAD

**Issue by ghost** [thepowersgang/cmdline_words_parser#2]
Hey thanks for writing this really useful crate! Sadly I noticed that updating to 0.2.0 causes my build on Windows is failing : (

Target and compiler:
 
stable-x86_64-pc-windows-msvc
rustc 1.42.0

```
Compiling cmdline_words_parser v0.2.0
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> src\lib.rs:84:35
   |
84 |         let _: &[u8] = <_ as ::std::os::unix::ffi::OsStrExt>::as_bytes(self);
   |                                         ^^^^ could not find `unix` in `os`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `cmdline_words_parser`.

To learn more, run the command again with --verbose.
```
I looked into it and it seems that std::os::unix::* is not available on windows platforms (https://doc.rust-lang.org/std/os/unix/index.html). Is line 84 "just" a safety check that can be disabled or rewritten on windows platforms? 

I use this crate indirectly via the https://crates.io/crates/easy_process crate which uses this crate with default features enabled. So disabling `std` is not possible here.

Thanks for your help! :)

**Comment by thepowersgang** [comment]
Fixed in v0.2.1
